const Smartphone = require('../models/Smartphone');

module.exports = {
    async index(req, res) {
        const smartphones = await Smartphone.findAll({
            attributes: ['id', 'name', 'brand']
        });

        return res.json(smartphones)
    },

    async store(req, res) {
        const { url,
            name,
            brand,
            mainimage,
            otherimages,
            os,
            chipset,
            cpu,
            gpu,
            externalmem,
            internalmem,
            antutu8,
            antutu7,
            geekbenchsingle5,	
            geekbenchmulti5,
            geekbenchsingle4,
            geekbenchmulti4,
            maincamera,
            mainespecifications,	
            mainfunctions,
            mainvideo,
            maindxomarkscore,	
            maindxomarkphoto,
            maindxomarkvideo,
            selfiecamera,
            selfieespecifications,	
            selfiefunctions,
            selfievideo,
            selfiedxomarkscore,
            selfiedxomarkphoto,
            selfiedxomarkvideo,
            technology,
            numbercolors,
            inches,
            screenarea,
            format,
            resolution,
            pixelsdensity,
            protection,
            screenextrafeatures,	
            release,
            dimensions,
            weight,
            material,
            colors,
            battery,
            batterylife,
            sim,
            network,
            speed,
            gprs,
            edge,
            wifi,
            gps,
            nfc,
            usb,
            bluetooth,
            irradiation,
            radio,
            headphonejack,	
            others,
            otherfeatures,
            sensors } = req.body;

        const smartphone = await Smartphone.create({ url,
            name,
            brand,
            mainimage,
            otherimages,
            os,
            chipset,
            cpu,
            gpu,
            externalmem,
            internalmem,
            antutu8,
            antutu7,
            geekbenchsingle5,	
            geekbenchmulti5,
            geekbenchsingle4,
            geekbenchmulti4,
            maincamera,
            mainespecifications,	
            mainfunctions,
            mainvideo,
            maindxomarkscore,	
            maindxomarkphoto,
            maindxomarkvideo,
            selfiecamera,
            selfieespecifications,	
            selfiefunctions,
            selfievideo,
            selfiedxomarkscore,
            selfiedxomarkphoto,
            selfiedxomarkvideo,
            technology,
            numbercolors,
            inches,
            screenarea,
            format,
            resolution,
            pixelsdensity,
            protection,
            screenextrafeatures,	
            release,
            dimensions,
            weight,
            material,
            colors,
            battery,
            batterylife,
            sim,
            network,
            speed,
            gprs,
            edge,
            wifi,
            gps,
            nfc,
            usb,
            bluetooth,
            irradiation,
            radio,
            headphonejack,	
            others,
            otherfeatures,
            sensors });

        return res.json(smartphone);
    }
}